### ISSUE TITLE
Rename repository to `website`

### ISSUE THREAD

**Issue by dkastl** [potree/potree.github.io#1]
Referencing https://github.com/potree/potree/issues/355

I think you could rename the repository from `potree.github.io` to just `website` for example. 

In the end the website would be accessible by "www.potree.org" or just "potree.org", and these settings for Github Pages can be just made with some configuration file.

**Comment by martinheidegger** [comment]
The default pattern by github for the website of an organization is "<org>.github.io". Using a different naming would just confuse people imho.

**Comment by dkastl** [comment]
I think, it would confuse people to use `potree.github.io` as a domain. I don't see a reason to use a subdomain of Github.

**Comment by martinheidegger** [comment]
It is mentioned in the first step when setting up a github page, if someone is confused then she didn't work with github _(imo)_: ![](https://gyazo.com/0f7cf3069f55b04aad910d252c2458d8.png)

>...  named _username.github.io_, where _username_ is your username (or organization name) on GitHub.

**Comment by martinheidegger** [comment]
Amendment: by keeping `potree.github.io` the domain `http://potree.github.io` will also redirect to whatever name is given in the CNAME file.

**Comment by dkastl** [comment]
OK, I agree, that it is maybe easier to use this repository name. When I setup the pgRouting GH Pages, this workflow was not supported by Github yet.
However, using a different repository name just requires a few additional settings ... probably. For example, when we want to make the documentation available under "docs.potree.org", it would be necessary anyway, no?

Here the settings of pgRouting, that has a repository named "website": https://github.com/pgRouting/website

![screenshot from 2017-07-13 06-10-34](https://user-images.githubusercontent.com/227762/28150008-adaaddac-67cc-11e7-942d-610450d38886.png)

**Comment by martinheidegger** [comment]
It is possible to set any `gh-pages` to point to a website but then the https://potree.github.io default subdomain will just point nowhere. With this repo name it will be later redirected to potree.org ;)

**Comment by martinheidegger** [comment]
Closing this issue, I think we are fine with potree.github.io, please reopen if you think this was premature.
