### ISSUE TITLE
HTTPS for custom domain

### ISSUE THREAD

**Issue by dkastl** [potree/potree.github.io#2]
HTTPS for custom domains is still not supported unfortunately by Github Pages, but there seem to be workarounds using CloudFlare: https://support.cloudflare.com

I want to setup HTTPS for the pgRouting websites as well, so I can help with this.
The only annoying part of CloudFlare is, that it requires another 3rd party account.

**Comment by martinheidegger** [comment]
While https would be nice to have: the homepage does not (yet) have any dynamic components which means we have no user data stored with it. _(giving it a low priority)_

**Comment by dkastl** [comment]
I agree, that there is no issue with private data sent, so it's not important to have it. I just heard that it may affect search ranking of Google for example, not to have HTTPS.

**Comment by martinheidegger** [comment]
The current website has some problems with static urls and https is not enabled on the `http://potree.org` website. While it is possible to fix those issues, it might be quicker and more effective, to just use cloudflare and enable https for the website. Setting up http://cloudflare.com.

Here is a small overview of how this should work. _(it is documented in depth on the cloudflare homepage)_

1. Get a cloudflare account.
2. Setup the potree.org domain.
3. Make sure that the DNS entries on cloudflare match the current DNS entries! _(usually mx entries might have a problem)_
4. Enable https _(https://support.cloudflare.com/hc/en-us/articles/201897700-Step-4-Recommended-First-Steps-for-all-Cloudflare-users#sslmode)_
5. Switch the Nameservers for the `potree.org` domain to the Nameservers mentioned in the cloudflare backend.
6. Wait up to 24h _(usually a lot quicker)_ until the nameserver change is propagated.

Done. This process takes me about 15 minutes. Even considering that it might take you longer it should be a reasonable step to ask. @potree do you think this would be a good way to go about it?

**Comment by midnight-dev** [comment]
Given a recent interest with VR (and with Firefox requiring HTTPS for its VR API), it may be worth revisiting this.

For what it's worth, using Amazon CloudFront to host static assets (from an S3 bucket) like images, scripts, and point clouds would be cheap and they can instantly issue a free cert.

This was a topic from several years ago, though. Maybe GitHub pages allows HTTPS for custom domains now?
