### ISSUE TITLE
Import old blog entries

### ISSUE THREAD

**Issue by martinheidegger** [potree/potree.github.io#4]
The old blog entries are stored in wordpress, it would be good to keep the links and not break any pages linking to those blog entries.

**Comment by potree** [comment]
How do posts on github pages work?
Is there some kind of cms or is it all static pages?

**Comment by martinheidegger** [comment]
Hello @potree, I just saw that you moved the homepage already. It would have been nice to get a notice since I worked (with pains) on an importer for the old page. 😅

**Comment by potree** [comment]
Hey Martin! Sorry about that :x 
Btw, I found it difficult to use githubs hosting service since it insists on https and the point clouds aren't hosted with https. Do you know if it's possible to disable this?

**Comment by martinheidegger** [comment]
Will answer in #2 _(since that issue is related to your problem)_
